### ISSUE TITLE
Buttons for New Arrivals, Sale, and Login are Non-functional

### ISSUE THREAD

**Issue by manwinderpreet0734** [Mansityagi130/TECHTEAM_PR16#1]
The buttons labeled "New Arrivals," "Sale," and "Login" on our website are currently not functioning. Users are unable to navigate to these sections, which impacts the overall user experience. To enhance the usability and functionality of our website, we need to implement the following:
1.Create a New Arrivals Page:
- Develop a dedicated page to display new arrival products.
- Ensure the New Arrivals button navigates to this page.
- Design the page to highlight the latest products.
2.Create a Sale Page:
- Develop a dedicated page to showcase products on sale.
- Ensure the Sale button navigates to this page.
- Include features such as sale duration.
3.Create a Login Page:
- Develop a user-friendly login page.
- Ensure the Login button navigates to this page.
- Include fields for email/username and password.

**Comment by Mansityagi130** [comment]
Done!!
