### ISSUE TITLE
Add Product Page and Add to Cart Page to Enhance User Experience

### ISSUE THREAD

**Issue by manwinderpreet0734** [Mansityagi130/TECHTEAM_PR16#13]
1.Add Product Page:
-Create a dedicated product page where users can view detailed information about each product.
2.Add to Cart Page:
-Develop an add-to-cart page that allows users to review and manage items they wish to purchase.

Benefits:
-Enhanced User Experience: Detailed product pages help users make informed decisions, and a dedicated cart page improves the shopping process.

**Comment by Mansityagi130** [comment]
Added the prescribed pages to enhance our user experience!!
